# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1  
kind: Service
metadata:
  name: eraft-kvserver
  labels:
    app: eraft-kvserver
spec:
  ports:
  - name: eraft-kvserver
    port: 8088
  clusterIP: None
  selector:
    app: eraft-kvserver
