# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1  
kind: Service
metadata:
  name: wellwood-blockserver
  labels:
    app: wellwood-blockserver
spec:
  ports:
  - name: wellwood-blockserver
    port: 8088
  clusterIP: None
  selector:
    app: wellwood-blockserver
