# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1  
kind: Service
metadata:
  name: wellwood-metaserver
  labels:
    app: wellwood-metaserver
spec:
  ports:
  - name: wellwood-metaserver
    port: 8088
  clusterIP: None
  selector:
    app: wellwood-metaserver
